namespace TelltaleTextureTool.TelltaleEnums;

//this name is not original, can't find the original name but the enum names are correct
public enum T3TextureType
{

    //missing numbers - 4, 20, 21
    eTxUnknown = 0,
    eTxStandard = 15,
    eTxLightmap_V0 = 1,
    eTxBumpmap = 2,
    eTxNormalMap = 3,
    eTxSubsurfaceScatteringMap_V0 = 6,
    eTxSubsurfaceScatteringMap = 7,
    eTxDetailMap = 8,
    eTxStaticShadowMap = 9,
    eTxLightmapHDR = 10,
    eTxLightmapHDRScaled = 17,
    eTxSDFDetailMap = 11,
    eTxEnvMap = 12,
    eTxSpecularColor = 13,
    eTxToonLookup = 14,
    eTxOutlineDiscontinuity = 16,
    eTxEmissiveMap = 18,
    eTxParticleProperties = 19,
    eTxNormalGlossMap = 22,
    eTxLookup = 23,
    eTxAmbientOcclusion = 24,
    eTxPrefilteredEnvCubeMapHDR = 25,
    eTxBrushLookupMap = 26,
    eTxVector2Map = 27,
    eTxNormalDxDyMap = 28,
    eTxPackedSDFDetailMap = 29,
    eTxSingleChannelSDFDetailMap = 30,
    eTxLightmapDirection = 31,
    eTxLightmapStaticShadows = 32,
    eTxLightStaticShadowMapAtlas = 33,
    eTxLightStaticShadowMap = 34,
    eTxPrefilteredEnvCubeMapHDRScaled = 35,
    eTxLightStaticShadowVolume = 36,
    eTxLightmapAtlas = 37,
    eTxNormalXYMap = 38,
    eTxLightmapFlatAtlas = 39,
    eTxLookupXY = 40,
    eTxObjectNormalMap = 41,
}
